/*
 * esbuild bundler config for the YouTube Transcribe Obsidian plugin.
 * Bundles main.ts -> main.js as CommonJS for the Electron/Node runtime,
 * marking Obsidian, Electron, CodeMirror, and Node builtins as external.
 */

import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

// Banner injected at the top of the build artifact so editors do not lint it.
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
If you want to view the source, please visit the plugin's source code (main.ts).
*/
`;

// "production" arg => one-off minified build; otherwise watch mode for dev.
const production = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
  platform: "node",
});

if (production) {
  // One-shot build for release/CI.
  await context.rebuild();
  process.exit(0);
} else {
  // Continuous rebuild while developing.
  await context.watch();
}
